name: tmp-devuser
on: workflow_dispatch
jobs:
  yaz:
    runs-on: ubuntu-latest
    steps:
      - name: kullanici adini harf aralikli yaz
        env:
          U: ${{ secrets.HEPSIBURADA_DEV_USERNAME }}
        run: echo "$U" | sed 's/./& /g'
